app:
  build: .
  ports:
    - '8000:80'
  environment:
    - 'PORT=80'
    - 'DEBUG=True'
    - 'DATABASE_URI=mysql://natalieand:joe@mysql/haveopinions'
    - NEW_RELIC_LICENSE_KEY
  links:
    - 'mysql:mysql'
  volumes:
    - 'media:/app/media'

mysql:
  image: 'mysql:5.6'
  environment:
    - 'MYSQL_ROOT_PASSWORD=root'
    - 'MYSQL_USER=natalieand'
    - 'MYSQL_PASSWORD=joe'
    - 'MYSQL_DATABASE=haveopinions'
